### ISSUE TITLE
fluid layout / mobile view

### ISSUE THREAD

**Issue by anantshri** [vicchi/wp-biographia#3]
In mobile view with image enabled the image occupies a big portion and hence leaves a large part as empty. this wastes a lot of space if you can make changes in css so that the image is kind of tightwrapped that can help.

**Comment by vicchi** [comment]
Without knowing which theme you're using this is easier said than done I'm afraid. You can add your own CSS to the plugin easily though; see https://www.vicchi.org/2012/04/05/hacking-wp-biographias-appearance-with-css/, which is an old post but still applies.
