### ISSUE TITLE
Widget not displaying all available authors at homepage

### ISSUE THREAD

**Issue by Myddna** [vicchi/wp-biographia#4]
Hello,

I've found that the widget does not display all authors when put in the sidebar at homepage, only the ones whose posts are currently displaying at that page.

I made some adjustments in the code but I understand that this should be done via an option in the widget (something like: "If displayed at home page, list all available authors")

If you like the idea, I coud post a patch including the option.

**Comment by vicchi** [comment]
It's been a while but I've recently started working on a major upgrade to this plugin, see https://wordpress.org/support/topic/major-plugin-update-now-in-public-beta/.

If you still have a patch, please rebase it on `v4` branch and fire off a pull request.
